### ISSUE TITLE
Checklist: multiple issues

### ISSUE THREAD

**Issue by mathieugouin** [mathieugouin/dhc6#8]
... Not working

**Comment by mathieugouin** [comment]
- [x] Generator switches not working
- [x] FWD tank fuel gauge indicates 0
- [x] AFT tank fuel gauge indicates 0
- [x] Fuel indicators return to prev. value

**Comment by mathieugouin** [comment]
merged.

**Comment by mathieugouin** [comment]
GEN ON/OFF not working yet

**Comment by mathieugouin** [comment]
merged
